### ISSUE TITLE
Provide package that can be built with ./configure

### ISSUE THREAD

**Issue by ericoporto** [xiph/theora#16]
The libtheora package here is different from the one in the downloads section of xiph : https://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2

This one can be built with `./configure` while the tags here cannot. Is it possible to upload proper tar ball?

**Comment by rillian** [comment]
To build straight from the repository you need to run `./autogen.sh` to create the configure script and associated files.

**Comment by ericoporto** [comment]
Thanks! I used it and passed arguments I used to pass to `./configure` and it worked. Before using autogen it kept asking about SDL1 and I didn't want to depend on it since I am using SDL2 but it worked without errors using `./autogen.sh`.

I had to migrate to GitHub because Xiph upgraded the TLS config on their servers and my pipeline uses Debian Jessie which has an old curl/openssl that is not compatible with the recent TLS change.

**Comment by rillian** [comment]
Glad you got it working.

We did indeed raise the minimum TLS level. Sorry for the inconvenience. You could always build your own curl/openssl packages if you need to maintain systems that old. It's just another couple of pipeline steps!

**Comment by ericoporto** [comment]
Thanks! I will look into it, it was a bit less trivial then I thought it would building openssl and curl, so for now I moved to using GitHub tar ball until I can figure out how to do it. I am closing since I got the information I needed. :)
