### ISSUE TITLE
Please make a release on github

### ISSUE THREAD

**Issue by jasjuang** [xiph/theora#4]
Is it possible to make a release on github? It will make integration to [vcpkg](https://github.com/Microsoft/vcpkg) a lot smoother. Thanks!

**Comment by tdaede** [comment]
Is just a tag fine, or do you want a downloadable release? If the latter, it would just be a copy of the latest archives in https://ftp.osuosl.org/pub/xiph/releases/theora/

We do tags for all of the other xiph projects (so I'd definitely want to add them back to theora) but not releases at the moment.

**Comment by jasjuang** [comment]
Tag will work. As long as there is something when I type `git describe --tags` it will be helpful

**Comment by rillian** [comment]
It looks like we don't have tags in the git repo. Someone would have to go through the svn tags and create new ones. I meant to do this but looks like I never got around to it?

Can you not package the [official tarballs](https://downloads.xiph.org/releases/theora/libtheora-1.1.1.zip)? That would be more appropriate anyway.

**Comment by jasjuang** [comment]
That's a little bit outdated, and the current master contains performance improvements and bugfixes (also MSVC-specific)

**Comment by rillian** [comment]
I see, you actually want to package straight out of git. Ok.

I added `v1.1.0` and `v1.1.1` tags, but they're not ancestors of the master branch, so that doesn't help with `git describe --tags`. I'll try to find the 1.2 alpha release and tag that as well.

**Comment by rillian** [comment]
Hopefully this will work for you. If not, please re-open.
```
$ git describe --tags --dirty
v1.2.0alpha1-129-gfa5707d
```

**Comment by jhasse** [comment]
I actually prefer the official tarballs, is there any chance they could be updated (e.g. an 1.2.0 release), too?
